---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}
  labels:
    app: {{ .Name }}
    env: {{ .Environment }}
    type: {{ .AppType }}
spec:
  replicas: {{ .Replicas }}
  selector:
    matchLabels:
        app: {{ .Name }}
  template:
    metadata:
      labels:
        app: {{ .Name }}
    spec:
      containers:
        - name: app
          image: {{ .Image }}
          args:
            - web
          env:
            - name: ENV
              value: {{ .Environment }}
