apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}
  labels:
    env: {{ .Environment }}
    app: {{ .Name }}
spec:
  replicas: {{ .Replicas }}
  selector:
    matchLabels:
        app: {{ .Name }}
  template:
    metadata:
      labels:
        app: {{ .Name }}
    spec:
      containers:
        - name: app
          image: {{ .Image }}
          args:
            - web
          env:
            - name: ENV
              value: {{ .Environment }}
      serviceAccountName: {{ .ServiceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .ServiceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Name }}@{{ .ServiceAccountProject }}.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ .ServiceAccount }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ .ServiceAccountProject }}
spec:
  displayName: {{ .ServiceAccount }}
  resourceID: {{ .ServiceAccount }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ .ServiceAccount }}-workload-identity
spec:
  member: serviceAccount:{{ .ServiceAccountProject }}.svc.id.goog[staging/{{ .ServiceAccount }}]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: {{ .ServiceAccount }}
