apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}
  labels:
    env: {{ .Environment }}
    app: {{ .Name }}
spec:
  replicas: {{ .Replicas }}
  selector:
    matchLabels:
        app: {{ .Name }}
  template:
    metadata:
      labels:
        app: {{ .Name }}
    spec:
      containers:
        - name: app
          image: {{ .Image }}
          args:
            - web
          env:
            - name: ENV
              value: {{ .Environment }}
      serviceAccountName: {{ .ServiceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .ServiceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Name }}@{{ .ServiceAccountProject }}.iam.gserviceaccount.com
