apiVersion: app.innoq.com/v1
kind: App
metadata:
  name: hello
  annotations:
    config.kubernetes.io/function: |
      container:
        image: app-creator:1.0.0
spec:
  size: medium
  image: test:123
  port: 8080
