apiVersion: platform.example.com/v1alpha1
kind: ExampleApp
metadata:
  name: simple-app-sample
  annotations:
    config.kubernetes.io/function: |
      container:
        image: ghcr.io/nissessenap/k8s-generator:v0.1.3
env: production
app:
  appType:
    - pubsub
  image: registry.example.com/path/to/simple-app-sample
  language: scala
